### ISSUE TITLE
NuGet packages

### ISSUE THREAD

**Issue by nick-strohm** [theumod/uMod#68]
Hey,

it would be pretty awesome if you allow us to install the uMod Libraries via NuGet to enhance plugin development a little bit.

For example, I think its a unnecessary time consuming task to check if the local libraries are in the correct place or if there is any update. NuGet does that automatically for you.

Have a great day!

**Comment by lukespragg** [comment]
You have been able to use NuGet for the past year+, we even use them with the projects.

**Comment by nick-strohm** [comment]
Well, thats not very good documented.
Thank you anyways. Now I know!
